CREATE TABLE `work_other`.`reservation_site_facility_mappings` (
  `reservation_site_facility_mapping_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_hospital_id` int unsigned NOT NULL,
  `reservation_hospital_name` varchar(255) NOT NULL,
  `exam_facility_id` bigint unsigned NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `mapping_note` text DEFAULT NULL,
  `created_by_app_user_id` bigint unsigned DEFAULT NULL,
  `updated_by_app_user_id` bigint unsigned DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`reservation_site_facility_mapping_id`),
  UNIQUE KEY `uq_reservation_site_facility_hospital` (`reservation_hospital_id`),
  KEY `idx_reservation_site_facility_exam` (`exam_facility_id`, `is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_ja_0900_as_cs;

CREATE TABLE `work_other`.`reservation_site_records` (
  `reservation_site_record_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_id` bigint unsigned NOT NULL COMMENT 'CSV id。予約システム全体の一意な予約ID',
  `event_id` bigint NOT NULL,
  `reservation_hospital_id` int unsigned NOT NULL,
  `reservation_hospital_name` varchar(255) DEFAULT NULL,
  `exam_facility_id` bigint unsigned DEFAULT NULL COMMENT '取込時の施設対応表による補助ID',
  `course_id` int unsigned DEFAULT NULL,
  `course_name` varchar(255) DEFAULT NULL,
  `reservation_date` date DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `reservation_status_raw` varchar(16) DEFAULT NULL,
  `cancelled_at` datetime DEFAULT NULL,
  `terminal_type_raw` varchar(16) DEFAULT NULL,
  `tax_included_price` decimal(12,0) DEFAULT NULL,
  `second_date` datetime DEFAULT NULL,
  `third_date` datetime DEFAULT NULL,
  `tel_timezone_raw` varchar(16) DEFAULT NULL,
  `tel_timezone_hour` tinyint unsigned DEFAULT NULL,
  `insurance_assoc_id_raw` varchar(20) DEFAULT NULL,
  `insurer_number_match` varchar(20) DEFAULT NULL,
  `insurance_assoc_name` varchar(255) DEFAULT NULL,
  `source_created_at` datetime DEFAULT NULL,
  `source_updated_at` datetime DEFAULT NULL,
  `applicant_id` int unsigned DEFAULT NULL,
  `hia_member_id` varchar(190) DEFAULT NULL COMMENT 'HIA加入者ID。加入者マスタとの照合キー',
  `applicant_fullname` varchar(255) DEFAULT NULL,
  `applicant_fullname_kana` varchar(255) DEFAULT NULL,
  `applicant_fullname_kana_match` varchar(255) DEFAULT NULL,
  `applicant_tel` varchar(64) DEFAULT NULL,
  `applicant_sex_raw` varchar(16) DEFAULT NULL,
  `applicant_birthday` date DEFAULT NULL,
  `postcode` varchar(16) DEFAULT NULL,
  `fulladdress` varchar(512) DEFAULT NULL,
  `insurance_symbol` varchar(190) DEFAULT NULL,
  `insurance_number` varchar(190) DEFAULT NULL,
  `insurance_symbol_match` varchar(190) DEFAULT NULL,
  `insurance_number_match` varchar(190) DEFAULT NULL,
  `canceller_raw` varchar(64) DEFAULT NULL,
  `hia_course_code` varchar(64) DEFAULT NULL,
  `hia_course_name` varchar(255) DEFAULT NULL,
  `course_total_price` decimal(12,0) DEFAULT NULL,
  `course_subsidy_amount` decimal(12,0) DEFAULT NULL,
  `row_sha256` char(64) NOT NULL,
  `first_seen_run_id` bigint unsigned NOT NULL,
  `last_seen_run_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`reservation_site_record_id`),
  UNIQUE KEY `uq_reservation_site_records_reservation` (`reservation_id`),
  KEY `idx_reservation_site_records_event` (`event_id`),
  KEY `idx_reservation_site_records_event_status` (`event_id`, `reservation_status_raw`, `hia_member_id`),
  KEY `idx_reservation_site_records_event_facility` (`event_id`, `exam_facility_id`, `hia_member_id`),
  KEY `idx_reservation_site_records_event_date` (`event_id`, `reservation_date`, `hia_member_id`),
  KEY `idx_reservation_site_records_hospital` (`reservation_hospital_id`),
  KEY `idx_reservation_site_records_hia_member` (`hia_member_id`),
  KEY `idx_reservation_site_records_kana` (`applicant_fullname_kana_match`),
  KEY `idx_reservation_site_records_insurance` (`insurer_number_match`, `insurance_symbol_match`, `insurance_number_match`),
  KEY `idx_reservation_site_records_hia_course` (`hia_course_code`),
  KEY `idx_reservation_site_records_last_run` (`last_seen_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_ja_0900_as_cs;

CREATE TABLE `work_other`.`reservation_site_record_options` (
  `reservation_site_record_option_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_site_record_id` bigint unsigned NOT NULL,
  `option_slot_no` tinyint unsigned NOT NULL,
  `option_hia_code` varchar(64) DEFAULT NULL,
  `option_name` varchar(255) DEFAULT NULL,
  `option_price` decimal(12,0) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `first_seen_run_id` bigint unsigned NOT NULL,
  `last_seen_run_id` bigint unsigned NOT NULL,
  `inactive_run_id` bigint unsigned DEFAULT NULL,
  `inactive_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`reservation_site_record_option_id`),
  UNIQUE KEY `uq_reservation_site_record_option_slot` (`reservation_site_record_id`, `option_slot_no`),
  KEY `idx_reservation_site_record_option_code` (`option_hia_code`, `is_active`),
  CONSTRAINT `fk_reservation_site_record_option_record` FOREIGN KEY (`reservation_site_record_id`)
    REFERENCES `work_other`.`reservation_site_records` (`reservation_site_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_ja_0900_as_cs;

CREATE TABLE `work_other`.`reservation_site_record_history` (
  `reservation_site_record_history_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `reservation_site_record_id` bigint unsigned NOT NULL,
  `run_id` bigint unsigned NOT NULL,
  `change_scope` varchar(16) NOT NULL DEFAULT 'RECORD',
  `option_slot_no` tinyint unsigned DEFAULT NULL,
  `column_name` varchar(190) NOT NULL,
  `old_value` text DEFAULT NULL,
  `new_value` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`reservation_site_record_history_id`),
  KEY `idx_reservation_site_record_history_record` (`reservation_site_record_id`),
  KEY `idx_reservation_site_record_history_run` (`run_id`),
  CONSTRAINT `fk_reservation_site_record_history_record` FOREIGN KEY (`reservation_site_record_id`)
    REFERENCES `work_other`.`reservation_site_records` (`reservation_site_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_ja_0900_as_cs;
