CREATE TABLE `dev_phr`.`staging_subscribers_hub` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `src_file` varchar(190) DEFAULT NULL,
  `src_row_no` int DEFAULT NULL,
  `src_line_no` int DEFAULT NULL,
  `import_run_id` bigint unsigned DEFAULT NULL,
  `processed_run_id` bigint unsigned DEFAULT NULL,
  `person_id_custom` varchar(190) DEFAULT NULL,
  `identity_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'compare / join 用 identity hash',
  `hia_subscriber_id` varchar(190) DEFAULT NULL COMMENT 'HIA加入者ID（DLフォーマット先頭列）',
  `name_kana_full` varchar(190) DEFAULT NULL,
  `name_kana_full_match` varchar(190) DEFAULT NULL COMMENT '氏名カナ全文match値',
  `name_kanji_full` varchar(190) DEFAULT NULL,
  `name_kanji_full_match` varchar(190) DEFAULT NULL COMMENT '氏名漢字全文match値',
  `name_kanji_family` varchar(190) DEFAULT NULL,
  `name_kanji_given` varchar(190) DEFAULT NULL,
  `name_kanji_middle` varchar(190) DEFAULT NULL,
  `name_kana_family` varchar(190) DEFAULT NULL,
  `name_kana_given` varchar(190) DEFAULT NULL,
  `name_kana_middle` varchar(190) DEFAULT NULL,
  `gender_code` varchar(190) DEFAULT NULL,
  `birth` date DEFAULT NULL COMMENT '日付型に変更',
  `insured_attribute_name` varchar(190) DEFAULT NULL,
  `relationship_name` varchar(190) DEFAULT NULL,
  `insurer_number` char(8) DEFAULT NULL,
  `insurance_symbol` varchar(190) DEFAULT NULL,
  `insurance_number` varchar(190) DEFAULT NULL,
  `insurance_branchnumber` varchar(190) DEFAULT NULL,
  `insurance_symbol_digits` int unsigned DEFAULT NULL COMMENT 'insurance_symbol から数字のみ抽出した派生キー（例: 埼-30→30、数字なし→NULL）',
  `qualification_acquired_date` date DEFAULT NULL,
  `qualification_lost_date` date DEFAULT NULL,
  `postal_code` varchar(190) DEFAULT NULL,
  `address_line` varchar(190) DEFAULT NULL,
  `building` varchar(190) DEFAULT NULL,
  `phone` varchar(190) DEFAULT NULL,
  `email` varchar(190) DEFAULT NULL,
  `employer_code` varchar(190) DEFAULT NULL,
  `department_code` varchar(190) DEFAULT NULL,
  `distribution_code` varchar(190) DEFAULT NULL,
  `employee_code` varchar(190) DEFAULT NULL,
  `connect_id` varchar(190) DEFAULT NULL,

  `apply_subscriber_id` bigint unsigned DEFAULT NULL COMMENT 'apply対象 subscribers.id',
  `apply_action` varchar(50) DEFAULT NULL COMMENT 'insert/update/noop/review',
  `apply_diff_columns` json DEFAULT NULL COMMENT '差分列一覧',
  `identity_match_status` varchar(50) DEFAULT NULL COMMENT 'identity compare結果',
  `address_diff_status` varchar(50) DEFAULT NULL COMMENT 'address compare結果',
  `contact_diff_status` varchar(50) DEFAULT NULL COMMENT 'contact compare結果',
  `apply_checked_at` datetime(3) DEFAULT NULL COMMENT 'prepare/compare 実行時刻',

  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `loaded_at` datetime(3) DEFAULT NULL,
  `processed_at` datetime(3) DEFAULT NULL,

  PRIMARY KEY (`id`),
  KEY `idx_stghub_import_run` (`import_run_id`),
  KEY `idx_stghub_processed_run` (`processed_run_id`),
  KEY `idx_stghub_insurer` (`insurer_number`),
  KEY `idx_stghub_namekana` (`name_kana_full`),
  KEY `idx_stghub_identity_hash` (`identity_hash`),
  KEY `idx_stghub_hia_subscriber_id` (`hia_subscriber_id`),
  KEY `idx_stghub_apply_action` (`apply_action`),
  KEY `idx_stghub_apply_subscriber_id` (`apply_subscriber_id`),
  KEY `idx_stghub_pending_apply` (`processed_run_id`, `apply_action`, `insurer_number`, `id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_ja_0900_as_cs;
