-- Add tumor marker items used by CSV health exam results.
-- CSV samples do not provide assay method, so these entries use the JLAC10
-- "other/unspecified method" style already used by optional exam items.

INSERT INTO `dev_phr`.`exam_item_master` (
  `namecode`,
  `item_name`,
  `xml_value_type`,
  `item_code_oid`,
  `result_code_oid`,
  `display_unit`,
  `ucum_unit`,
  `method_name`,
  `category_name`,
  `data_type_label`,
  `xml_method_code`,
  `xpath_template`,
  `value_method`,
  `nullflavor_allowed`,
  `importance`,
  `importance_group`,
  `notes`,
  `update_type`,
  `update_reason`,
  `source_last_updated`,
  `kubun_no`,
  `kubun_name`,
  `jun_no`,
  `identity_item_code`,
  `identity_item_name`,
  `annex2_exec_requirement`,
  `annex2_legal_report_flag`,
  `cda_section_code_default`
) VALUES
(
  '5D130000002399901',
  'CA19-9',
  'PQ',
  '1.2.392.200119.6.1005',
  NULL,
  'U/ml',
  'U/mL',
  'その他',
  'がん検診・生体検査等',
  '数字',
  '5D13020009',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'JLAC10: 5D130 CA19-9, serum, other/unspecified method, quantitative value.',
  '追加',
  'CSV健診結果取込で小禄病院のCA19-9を受けるため追加',
  '2026-07-29',
  200,
  'がん検診・生体検査等',
  1491,
  '5D130',
  'ＣＡ１９－９',
  NULL,
  0,
  '01990'
),
(
  '5D100000002399901',
  'CA125',
  'PQ',
  '1.2.392.200119.6.1005',
  NULL,
  'U/ml',
  'U/mL',
  'その他',
  'がん検診・生体検査等',
  '数字',
  '5D10020009',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'JLAC10: 5D100 CA125, serum, other/unspecified method, quantitative value.',
  '追加',
  'CSV健診結果取込で小禄病院のCA125を受けるため追加',
  '2026-07-29',
  200,
  'がん検診・生体検査等',
  1492,
  '5D100',
  'ＣＡ１２５',
  NULL,
  0,
  '01990'
)
ON DUPLICATE KEY UPDATE
  `item_name` = VALUES(`item_name`),
  `xml_value_type` = VALUES(`xml_value_type`),
  `item_code_oid` = VALUES(`item_code_oid`),
  `result_code_oid` = VALUES(`result_code_oid`),
  `display_unit` = VALUES(`display_unit`),
  `ucum_unit` = VALUES(`ucum_unit`),
  `method_name` = VALUES(`method_name`),
  `category_name` = VALUES(`category_name`),
  `data_type_label` = VALUES(`data_type_label`),
  `xml_method_code` = VALUES(`xml_method_code`),
  `notes` = VALUES(`notes`),
  `update_type` = VALUES(`update_type`),
  `update_reason` = VALUES(`update_reason`),
  `source_last_updated` = VALUES(`source_last_updated`),
  `kubun_no` = VALUES(`kubun_no`),
  `kubun_name` = VALUES(`kubun_name`),
  `jun_no` = VALUES(`jun_no`),
  `identity_item_code` = VALUES(`identity_item_code`),
  `identity_item_name` = VALUES(`identity_item_name`),
  `annex2_exec_requirement` = VALUES(`annex2_exec_requirement`),
  `annex2_legal_report_flag` = VALUES(`annex2_legal_report_flag`),
  `cda_section_code_default` = VALUES(`cda_section_code_default`),
  `updated_at` = CURRENT_TIMESTAMP(6);
