-- Add optional CLIA tumor marker exam_item_master rows promoted from m4 normalize fixtures.
-- These are method-specific variants of CA125 and CA19-9 and are accepted as exam result entries.

INSERT INTO `dev_phr`.`exam_item_master` (
  `namecode`,
  `item_name`,
  `xml_value_type`,
  `item_code_oid`,
  `result_code_oid`,
  `display_unit`,
  `ucum_unit`,
  `method_name`,
  `category_name`,
  `data_type_label`,
  `xml_method_code`,
  `nullflavor_allowed`,
  `notes`,
  `update_type`,
  `update_reason`,
  `source_last_updated`,
  `kubun_no`,
  `kubun_name`,
  `jun_no`,
  `identity_item_code`,
  `identity_item_name`,
  `annex2_exec_requirement`,
  `annex2_legal_report_flag`,
  `cda_section_code_default`
) VALUES
('5D100000002305101', 'CA125', 'PQ', '1.2.392.200119.6.1005', NULL, 'U/ml', 'U/mL', 'CLIA', 'がん検診・生体検査等', '数字', '5D10020005', NULL, 'JLAC10 optional tumor marker CLIA item added from normalize error fixture.', '追加', 'CSV/XML健診結果取込の任意腫瘍マーカー値を受けるため追加', '2026-08-06', 200, '任意追加項目', 1542, '5D100', 'CA125', NULL, 0, '01990'),
('5D130000002305101', 'CA19-9', 'PQ', '1.2.392.200119.6.1005', NULL, 'U/ml', 'U/mL', 'CLIA', 'がん検診・生体検査等', '数字', '5D13020005', NULL, 'JLAC10 optional tumor marker CLIA item added from normalize error fixture.', '追加', 'CSV/XML健診結果取込の任意腫瘍マーカー値を受けるため追加', '2026-08-06', 200, '任意追加項目', 1543, '5D130', 'CA19-9', NULL, 0, '01990')
ON DUPLICATE KEY UPDATE
  `item_name` = VALUES(`item_name`),
  `xml_value_type` = VALUES(`xml_value_type`),
  `item_code_oid` = VALUES(`item_code_oid`),
  `result_code_oid` = VALUES(`result_code_oid`),
  `display_unit` = VALUES(`display_unit`),
  `ucum_unit` = VALUES(`ucum_unit`),
  `method_name` = VALUES(`method_name`),
  `category_name` = VALUES(`category_name`),
  `data_type_label` = VALUES(`data_type_label`),
  `xml_method_code` = VALUES(`xml_method_code`),
  `nullflavor_allowed` = VALUES(`nullflavor_allowed`),
  `notes` = VALUES(`notes`),
  `update_type` = VALUES(`update_type`),
  `update_reason` = VALUES(`update_reason`),
  `source_last_updated` = VALUES(`source_last_updated`),
  `kubun_no` = VALUES(`kubun_no`),
  `kubun_name` = VALUES(`kubun_name`),
  `jun_no` = VALUES(`jun_no`),
  `identity_item_code` = VALUES(`identity_item_code`),
  `identity_item_name` = VALUES(`identity_item_name`),
  `annex2_exec_requirement` = VALUES(`annex2_exec_requirement`),
  `annex2_legal_report_flag` = VALUES(`annex2_legal_report_flag`),
  `cda_section_code_default` = VALUES(`cda_section_code_default`),
  `updated_at` = CURRENT_TIMESTAMP(6);
