-- Add urine pH as a JLAC10 fraction of general urinalysis.
-- Source interpretation:
--   JLAC10 1A990-0000-003-000-52
--   1A990 = urine qualitative/semiquantitative, 003 = freshly voided urine,
--   000 = method not specified, result identifier 52 = pH.

INSERT INTO `dev_phr`.`exam_item_master` (
  `namecode`,
  `item_name`,
  `xml_value_type`,
  `item_code_oid`,
  `result_code_oid`,
  `display_unit`,
  `ucum_unit`,
  `method_name`,
  `category_name`,
  `data_type_label`,
  `xml_method_code`,
  `xpath_template`,
  `value_method`,
  `nullflavor_allowed`,
  `importance`,
  `importance_group`,
  `notes`,
  `update_type`,
  `update_reason`,
  `source_last_updated`,
  `kubun_no`,
  `kubun_name`,
  `jun_no`,
  `identity_item_code`,
  `identity_item_name`,
  `annex2_exec_requirement`,
  `annex2_legal_report_flag`,
  `cda_section_code_default`
) VALUES (
  '1A990000000300052',
  '尿pH',
  'PQ',
  '1.2.392.200119.6.1005',
  NULL,
  NULL,
  NULL,
  '尿一般物質定性半定量検査',
  '尿検査',
  '数字',
  '1A99000000',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'JLAC10: 1A990-0000-003-000-52. 尿一般物質定性半定量検査の結果識別52(pH)。',
  '追加',
  'CSV健診結果取込で小禄病院の尿pHを受けるため追加',
  '2026-07-29',
  70,
  '尿検査',
  835,
  '1A990',
  '尿一般物質定性半定量検査',
  NULL,
  0,
  '01990'
)
ON DUPLICATE KEY UPDATE
  `item_name` = VALUES(`item_name`),
  `xml_value_type` = VALUES(`xml_value_type`),
  `item_code_oid` = VALUES(`item_code_oid`),
  `result_code_oid` = VALUES(`result_code_oid`),
  `display_unit` = VALUES(`display_unit`),
  `ucum_unit` = VALUES(`ucum_unit`),
  `method_name` = VALUES(`method_name`),
  `category_name` = VALUES(`category_name`),
  `data_type_label` = VALUES(`data_type_label`),
  `xml_method_code` = VALUES(`xml_method_code`),
  `notes` = VALUES(`notes`),
  `update_type` = VALUES(`update_type`),
  `update_reason` = VALUES(`update_reason`),
  `source_last_updated` = VALUES(`source_last_updated`),
  `kubun_no` = VALUES(`kubun_no`),
  `kubun_name` = VALUES(`kubun_name`),
  `jun_no` = VALUES(`jun_no`),
  `identity_item_code` = VALUES(`identity_item_code`),
  `identity_item_name` = VALUES(`identity_item_name`),
  `annex2_exec_requirement` = VALUES(`annex2_exec_requirement`),
  `annex2_legal_report_flag` = VALUES(`annex2_legal_report_flag`),
  `cda_section_code_default` = VALUES(`cda_section_code_default`),
  `updated_at` = CURRENT_TIMESTAMP(6);
